modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "tfother"
version = "1.3.0"
displayName = "TFother"
authors = "Timefield"
description = '''
Divers ajouts Timefield. PNJ Slime (wiki Tensura) et PNJ Bob (wiki MineColonies) qui ouvrent un wiki intégré en jeu quand on leur parle, et Tiplouf, PNJ IA qui répond aux questions sur Tensura.
'''

[[dependencies.tfother]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfother]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfother]]
modId = "patchouli"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfother]]
modId = "voicechat"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
