modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "tfother"
version = "1.0.1"
displayName = "TFother"
authors = "Timefield"
description = '''
Divers ajouts Timefield. PNJ Slime (wiki Tensura) et PNJ Bob (wiki MineColonies) qui ouvrent le wiki officiel quand on leur parle.
'''

[[dependencies.tfother]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfother]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
