package fr.timefield.tfother.tiplouf;

import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import com.mojang.logging.LogUtils;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.stream.IntStream;
import net.neoforged.fml.loading.FMLPaths;
import org.slf4j.Logger;

/**
 * Tensura knowledge base (generated by tools/tiplouf/build_knowledge.py).
 *
 * <p>Search combines embeddings (semantic, works across French/English) with a BM25 keyword
 * score (exact item names). Embeddings are computed once and cached in
 * config/tfother/tiplouf-embeddings.bin; until they are ready, search is keyword only.
 */
public final class KnowledgeBase {
    private static final Logger LOGGER = LogUtils.getLogger();
    private static final String RESOURCE = "/data/tfother/tiplouf/knowledge.json";
    private static final int CACHE_MAGIC = 0x7F1A0F01;
    private static final int EMBED_BATCH = 200;
    private static final float KEYWORD_WEIGHT = 0.15F;
    private static final double BM25_K1 = 1.2;
    private static final double BM25_B = 0.75;
    private static final Set<String> STOP_WORDS = Set.copyOf(List.of(
            "le", "la", "les", "un", "une", "des", "de", "du", "et", "ou", "en", "au", "aux", "je", "tu", "il",
            "on", "ce", "ca", "est", "que", "qui", "quoi", "comment", "pour", "par", "sur", "dans", "avec", "mon",
            "ma", "mes", "me", "moi", "te", "se", "sa", "son", "ses", "ne", "pas", "plus", "faire", "fait", "peut",
            "the", "of", "to", "and", "or", "in", "on", "is", "it", "for", "with", "how", "what", "can", "do", "an"));

    public record Chunk(String title, String text, String source) {
    }

    private static List<Chunk> chunks = List.of();
    private static String hash = "";
    private static List<Map<String, Integer>> termFreqs = List.of();
    private static Map<String, Integer> docFreqs = Map.of();
    private static int[] docLengths = new int[0];
    private static double avgLength;
    private static volatile float[][] vectors;

    private KnowledgeBase() {
    }

    /** Loads the chunks and the keyword index. Embeddings are loaded later by {@link #prepareEmbeddings()}. */
    public static synchronized void load() {
        if (!chunks.isEmpty()) {
            return;
        }
        try (InputStream in = KnowledgeBase.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                LOGGER.error("[Tiplouf] {} is missing from the jar", RESOURCE);
                return;
            }
            byte[] bytes = in.readAllBytes();
            hash = HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
            List<Chunk> list = new ArrayList<>();
            for (JsonElement e : JsonParser.parseString(new String(bytes, StandardCharsets.UTF_8)).getAsJsonArray()) {
                var o = e.getAsJsonObject();
                list.add(new Chunk(o.get("title").getAsString(), o.get("text").getAsString(), o.get("source").getAsString()));
            }
            buildKeywordIndex(list);
            chunks = List.copyOf(list);
            LOGGER.info("[Tiplouf] {} knowledge chunks loaded", chunks.size());
        } catch (IOException | NoSuchAlgorithmException e) {
            LOGGER.error("[Tiplouf] Could not load the knowledge base", e);
        }
    }

    /** Loads cached embeddings or computes them (in the background). */
    public static CompletableFuture<Void> prepareEmbeddings() {
        String model = TiploufConfig.EMBEDDING_MODEL.get();
        if (chunks.isEmpty() || model.isBlank() || !OpenAiClient.isConfigured()) {
            return CompletableFuture.completedFuture(null);
        }
        String key = model + "|" + TiploufConfig.EMBEDDING_DIMENSIONS.get() + "|" + hash;
        Path cache = FMLPaths.CONFIGDIR.get().resolve("tfother").resolve("tiplouf-embeddings.bin");
        float[][] cached = readCache(cache, key);
        if (cached != null) {
            vectors = cached;
            LOGGER.info("[Tiplouf] Embeddings loaded from cache");
            return CompletableFuture.completedFuture(null);
        }
        LOGGER.info("[Tiplouf] Computing embeddings for {} chunks...", chunks.size());
        float[][] result = new float[chunks.size()][];
        CompletableFuture<Void> chain = CompletableFuture.completedFuture(null);
        for (int start = 0; start < chunks.size(); start += EMBED_BATCH) {
            int from = start;
            int to = Math.min(chunks.size(), start + EMBED_BATCH);
            List<String> inputs = chunks.subList(from, to).stream().map(c -> c.title() + "\n" + c.text()).toList();
            chain = chain.thenCompose(v -> OpenAiClient.embed(inputs))
                    .thenAccept(batch -> System.arraycopy(batch, 0, result, from, batch.length));
        }
        return chain.thenRun(() -> {
            vectors = result;
            writeCache(cache, key, result);
            LOGGER.info("[Tiplouf] Embeddings ready");
        }).exceptionally(e -> {
            LOGGER.warn("[Tiplouf] Embeddings unavailable, keyword search only: {}", e.getMessage());
            return null;
        });
    }

    /** Returns the chunks most relevant to the query. */
    public static CompletableFuture<List<Chunk>> search(String query, int limit) {
        if (chunks.isEmpty()) {
            return CompletableFuture.completedFuture(List.of());
        }
        double[] keyword = keywordScores(query);
        float[][] vecs = vectors;
        if (vecs == null) {
            return CompletableFuture.completedFuture(top(keyword, limit));
        }
        return OpenAiClient.embed(List.of(query)).thenApply(q -> {
            double max = 0;
            for (double s : keyword) {
                max = Math.max(max, s);
            }
            double[] scores = new double[vecs.length];
            for (int i = 0; i < vecs.length; i++) {
                scores[i] = dot(q[0], vecs[i]) + (max > 0 ? KEYWORD_WEIGHT * keyword[i] / max : 0);
            }
            return top(scores, limit);
        }).exceptionally(e -> {
            LOGGER.warn("[Tiplouf] Query embedding failed, keyword search only: {}", e.getMessage());
            return top(keyword, limit);
        });
    }

    private static List<Chunk> top(double[] scores, int limit) {
        return IntStream.range(0, scores.length)
                .filter(i -> scores[i] > 0)
                .boxed()
                .sorted(Comparator.comparingDouble((Integer i) -> scores[i]).reversed())
                .limit(limit)
                .map(chunks::get)
                .toList();
    }

    private static float dot(float[] a, float[] b) {
        float sum = 0;
        for (int i = 0; i < a.length; i++) {
            sum += a[i] * b[i];
        }
        return sum;
    }

    // --- Keyword search (BM25, title counted three times) ---

    private static void buildKeywordIndex(List<Chunk> list) {
        List<Map<String, Integer>> tfs = new ArrayList<>(list.size());
        Map<String, Integer> dfs = new HashMap<>();
        int[] lengths = new int[list.size()];
        long total = 0;
        for (Chunk c : list) {
            Map<String, Integer> tf = new HashMap<>();
            List<String> title = tokenize(c.title());
            for (int i = 0; i < 3; i++) {
                title.forEach(t -> tf.merge(t, 1, Integer::sum));
            }
            tokenize(c.text()).forEach(t -> tf.merge(t, 1, Integer::sum));
            tf.keySet().forEach(t -> dfs.merge(t, 1, Integer::sum));
            lengths[tfs.size()] = tf.values().stream().mapToInt(Integer::intValue).sum();
            total += lengths[tfs.size()];
            tfs.add(tf);
        }
        termFreqs = tfs;
        docFreqs = dfs;
        docLengths = lengths;
        avgLength = list.isEmpty() ? 1 : (double) total / list.size();
    }

    private static double[] keywordScores(String query) {
        double[] scores = new double[termFreqs.size()];
        int n = termFreqs.size();
        for (String term : Set.copyOf(tokenize(query))) {
            Integer df = docFreqs.get(term);
            if (df == null) {
                continue;
            }
            double idf = Math.log(1 + (n - df + 0.5) / (df + 0.5));
            for (int i = 0; i < n; i++) {
                Integer tf = termFreqs.get(i).get(term);
                if (tf != null) {
                    double norm = 1 - BM25_B + BM25_B * docLengths[i] / avgLength;
                    scores[i] += idf * tf * (BM25_K1 + 1) / (tf + BM25_K1 * norm);
                }
            }
        }
        return scores;
    }

    static List<String> tokenize(String text) {
        String normalized = Normalizer.normalize(text.toLowerCase(Locale.ROOT), Normalizer.Form.NFD)
                .replaceAll("\\p{M}", "");
        List<String> tokens = new ArrayList<>();
        for (String t : normalized.split("[^a-z0-9]+")) {
            if (t.length() > 1 && !STOP_WORDS.contains(t)) {
                tokens.add(t.length() > 4 && t.endsWith("s") ? t.substring(0, t.length() - 1) : t);
            }
        }
        return tokens;
    }

    // --- Embedding cache ---

    private static float[][] readCache(Path file, String key) {
        if (!Files.exists(file)) {
            return null;
        }
        try (DataInputStream in = new DataInputStream(new BufferedInputStream(Files.newInputStream(file)))) {
            if (in.readInt() != CACHE_MAGIC || !in.readUTF().equals(key)) {
                return null;
            }
            int count = in.readInt();
            int dims = in.readInt();
            if (count != chunks.size()) {
                return null;
            }
            float[][] result = new float[count][dims];
            for (float[] v : result) {
                for (int i = 0; i < dims; i++) {
                    v[i] = in.readFloat();
                }
            }
            return result;
        } catch (IOException e) {
            LOGGER.warn("[Tiplouf] Unreadable embedding cache, recomputing", e);
            return null;
        }
    }

    private static void writeCache(Path file, String key, float[][] data) {
        try {
            Files.createDirectories(file.getParent());
            try (DataOutputStream out = new DataOutputStream(new BufferedOutputStream(Files.newOutputStream(file)))) {
                out.writeInt(CACHE_MAGIC);
                out.writeUTF(key);
                out.writeInt(data.length);
                out.writeInt(data[0].length);
                for (float[] v : data) {
                    for (float x : v) {
                        out.writeFloat(x);
                    }
                }
            }
        } catch (IOException e) {
            LOGGER.warn("[Tiplouf] Could not save the embedding cache", e);
        }
    }
}
